-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Jul 27, 2024 at 12:25 PM
-- Server version: 10.11.8-MariaDB-cll-lve
-- PHP Version: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `u496524825_matoshriagroex`
--

-- --------------------------------------------------------

--
-- Table structure for table `blog`
--

CREATE TABLE `blog` (
  `id` int(100) NOT NULL,
  `keyword` varchar(256) NOT NULL,
  `title` varchar(256) NOT NULL,
  `message` text NOT NULL,
  `metadata` text NOT NULL,
  `image` varchar(256) NOT NULL,
  `slug` varchar(256) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `blog`
--

INSERT INTO `blog` (`id`, `keyword`, `title`, `message`, `metadata`, `image`, `slug`) VALUES
(49, 'Banana exporter in Iraq', 'Best Banana exporter in Iraq', '<p>Bananas offer a range of health benefits due to their rich nutrient profile. Here are some key benefits of including bananas in your diet:\r\n\r\n1. Nutrient-Rich:\r\nVitamins and Minerals: Bananas are a good source of several vitamins and minerals, including vitamin C, vitamin B6, potassium, manganese, and dietary fiber.\r\n2. Heart Health:\r\nPotassium: High potassium intake is linked to a reduced risk of high blood pressure, which is a major risk factor for heart disease.</p>', 'Vitamins and Minerals: Bananas are a good source of several vitamins and minerals, including vitamin C, vitamin B6, potassium, manganese, and dietary fiber.', '', 'Banana-exporter-in-Iraq'),
(50, 'Banana exporter in Iran', 'Best Banana exporter in Iran', '<p>Digestive Health:\r\nDietary Fiber: Bananas are rich in dietary fiber, which helps support digestive health by promoting regular bowel movements and relieving constipation.\r\n Energy Boost:\r\nCarbohydrates: Bananas are a convenient source of energy due to their natural sugars (fructose, glucose, and sucrose) and carbohydrates.</p>', 'Bananas are rich in dietary fiber, which helps support digestive health by promoting regular bowel movements and relieving constipation.\r\n\r\n', '', 'Banana-exporter-in-Iran'),
(51, 'Banana exporter in UAE', 'Best Banana exporter in UAE', '<p>. Improved Mood and Stress Reduction:\r\nVitamin B6: This vitamin helps the body produce serotonin, which is known to improve mood and reduce stress levels.\r\n Exercise Performance:\r\nElectrolytes: Bananas contain electrolytes such as potassium, which can help maintain proper muscle function and prevent cramps during exercise.</p>', 'Bananas are a popular and nutritious fruit enjoyed worldwide. They are known for their sweet taste, convenience, and numerous health benefits. Here are some key points about bananas:', '', 'Banana-exporter-in-UAE'),
(52, 'Banana exporter in Oman', 'Best Banana exporter in Oman', '<p>Skin and Hair Health:\r\nVitamin C: This antioxidant vitamin is essential for collagen production, promoting healthy skin and hair.\r\n8. Weight Management:\r\nLow in Calories: Bananas are relatively low in calories but provide a feeling of fullness due to their fiber content, making them a satisfying snack option.\r\n9. Kidney Health:\r\nPotassium Regulation: Adequate potassium intake from foods like bananas may help support kidney function and reduce the risk of kidney stones.\r\n10. Immune System Support:\r\nAntioxidants: Bananas contain antioxidants like vitamin C and dopamine, which help neutralize harmful free radicals in the body and support overall immune function.</p>', 'Bananas change in flavor and texture as they ripen. Green bananas are more starchy and less sweet, while yellow bananas are sweeter and easier to digest. Overripe bananas with brown spots are ideal for baking.', '', 'Banana-exporter-in-Oman'),
(54, 'Banana exporter in Uzbekistan', 'Banana exporter in Uzbekistan', '<p>Bananas are one of the world\'s most popular fruits, loved for their convenience, versatility, and numerous health benefits. Here\'s a concise overview of bananas:\r\n\r\nOverview\r\nBotanical Name: Musa spp.\r\nOrigin: Native to Southeast Asia, bananas are now cultivated in tropical regions worldwide.\r\nNutritional Profile\r\nCalories: Approximately 105 calories per medium-sized banana.\r\nCarbohydrates: Rich in natural sugars (glucose, fructose, sucrose) and dietary fiber.\r\nVitamins and Minerals: Good source of vitamin C, vitamin B6, potassium, manganese, and magnesium.</p>', 'Nutritional Benefits: Bananas are rich in potassium, which is essential for heart health and muscle function. They also contain vitamins C and B6, as well as fiber, which aids digestion.', '', 'Banana-exporter-in-Uzbekistan'),
(55, 'Banana exporter in Saudi Arab', 'Best Banana exporter in Saudi Arab', '<p>Health Benefits\r\nHeart Health: High potassium content helps regulate blood pressure and heart function.\r\n\r\nDigestive Health: Fiber promotes healthy digestion and may help prevent constipation.\r\n\r\nEnergy Boost: Natural sugars provide quick energy, making bananas an ideal pre- or post-workout snack.\r\n\r\nMood and Stress Relief: Contains vitamin B6, which helps in the production of serotonin, improving mood and reducing stress.\r\n\r\nNutrient Absorption: The soluble fiber in bananas aids in nutrient absorption and digestive health.</p>', 'Cultural Significance: Bananas are culturally significant in many regions, often used in rituals, ceremonies, and traditional medicine.', '', 'Banana-exporter-in-Saudi-Arab'),
(56, 'Banana exporter in qatar', 'Best Banana exporter in qatar', '<p>Culinary Uses\r\nFresh Consumption: Eaten raw as a snack or added to cereals, yogurt, and salads.\r\nCooking: Used in baking (e.g., banana bread, muffins), desserts, smoothies, and savory dishes (e.g., plantains).\r\nVarieties\r\nCavendish Banana: Most common variety worldwide, typically eaten fresh.\r\nPlantains: Larger and starchier, often cooked before consumption.\r\nFun Facts\r\nBananas are technically berries botanically classified as \"false berries.\"\r\nThey are a staple food for more than 400 million people worldwide.</p>', 'Bananas can be eaten on their own as a quick snack or used in various recipes. They are commonly added to smoothies, yogurt, cereals, and baked goods like banana bread.', '', 'Banana-exporter-in-qatar'),
(57, 'Banana exporter in Maldives', 'Best Banana exporter in Maldives', '<p>Cultural Significance\r\nImportant in many cuisines globally, from desserts to savory dishes.\r\nSymbolizes hospitality in some cultures and plays a role in traditional ceremonies.\r\nSustainability\r\nChallenges include diseases affecting crops, such as Panama disease.\r\nEfforts in sustainable farming practices, fair trade, and biodiversity conservation are crucial.\r\nConclusion\r\nBananas are not just a delicious and nutritious fruit but also play a significant role in global agriculture and cultural heritage. Whether eaten fresh, blended into a smoothie, or used in cooking, bananas offer a versatile and healthful addition to any diet.</p>', 'Bananas are rich in dietary fiber, which helps support digestive health by promoting regular bowel movements and relieving constipation.\r\n\r\n', '', 'Banana-exporter-in-Maldives'),
(58, 'Banana exporter in Kuwait', 'Best Banana exporter in Kuwait', '<p>Bananas offer a range of health benefits due to their rich nutrient profile. Here are some key benefits of including bananas in your diet:\r\n\r\n1. Nutrient-Rich:\r\nVitamins and Minerals: Bananas are a good source of several vitamins and minerals, including vitamin C, vitamin B6, potassium, manganese, and dietary fiber.\r\n2. Heart Health:\r\nPotassium: High potassium intake is linked to a reduced risk of high blood pressure, which is a major risk factor for heart disease.</p>', 'Energy Boost: Due to their natural sugars (fructose, glucose, and sucrose), bananas provide a quick source of energy, making them a favorite among athletes.', '', 'Banana-exporter-in-Kuwait'),
(59, 'Banana exporter in Nepal', 'Best Banana exporter in Nepal', '<p>Improved Mood and Stress Reduction:\r\nVitamin B6: This vitamin helps the body produce serotonin, which is known to improve mood and reduce stress levels.\r\n Exercise Performance:\r\nElectrolytes: Bananas contain electrolytes such as potassium, which can help maintain proper muscle function and prevent cramps during exercise.</p>', 'Bananas are rich in dietary fiber, which helps support digestive health by promoting regular bowel movements and relieving constipation.\r\n', '', 'Banana-exporter-in-Nepal'),
(60, 'Banana exporter in USA', 'Best Banana exporter in USA', '<p>Skin and Hair Health:\r\nVitamin C: This antioxidant vitamin is essential for collagen production, promoting healthy skin and hair.\r\n8. Weight Management:\r\nLow in Calories: Bananas are relatively low in calories but provide a feeling of fullness due to their fiber content, making them a satisfying snack option.\r\n9. Kidney Health:\r\nPotassium Regulation: Adequate potassium intake from foods like bananas may help support kidney function and reduce the risk of kidney stones.\r\n10. Immune System Support:\r\nAntioxidants: Bananas contain antioxidants like vitamin C and dopamine, which help neutralize harmful free radicals in the body and support overall immune function.<p>', 'Bananas are rich in dietary fiber, which helps support digestive health by promoting regular bowel movements and relieving constipation.\r\n', '', 'Banana-exporter-in-USA'),
(61, 'Banana exporter inGermany', 'Best Banana exporter inGermany', '<p>Bananas are one of the world\'s most popular fruits, loved for their convenience, versatility, and numerous health benefits. Here\'s a concise overview of bananas:\r\n\r\nOverview\r\nBotanical Name: Musa spp.\r\nOrigin: Native to Southeast Asia, bananas are now cultivated in tropical regions worldwide.\r\nNutritional Profile\r\nCalories: Approximately 105 calories per medium-sized banana.\r\nCarbohydrates: Rich in natural sugars (glucose, fructose, sucrose) and dietary fiber.\r\nVitamins and Minerals: Good source of vitamin C, vitamin B6, potassium, manganese, and magnesium.</p>', 'Bananas are a popular fruit known for their yellow peel and sweet taste. They\'re packed with potassium, fiber, and vitamins, making them a healthy snack. Plus, they\'re versatile—you can eat them as they are, blend them into smoothies, bake them into bread, or even use them in savory dishes. What\'s your favorite way to enjoy a banana', '', 'Banana-exporter-inGermany'),
(62, 'Banana exporter in Singapore', 'Best Banana exporter in Singapore', '<p>Health Benefits\r\nHeart Health: High potassium content helps regulate blood pressure and heart function.\r\n\r\nDigestive Health: Fiber promotes healthy digestion and may help prevent constipation.\r\n\r\nEnergy Boost: Natural sugars provide quick energy, making bananas an ideal pre- or post-workout snack.\r\n\r\nMood and Stress Relief: Contains vitamin B6, which helps in the production of serotonin, improving mood and reducing stress.\r\n\r\nNutrient Absorption: The soluble fiber in bananas aids in nutrient absorption and digestive health.</p>', 'Bananas, with their vibrant yellow peel and soft, creamy flesh, are nature\'s convenient and nutritious snack. Packed with potassium, fiber, and essential vitamins like C and B6, they offer a burst of energy and promote overall well-being. ', '', 'Banana-exporter-in-Singapore'),
(63, 'Banana exporter in United kingdom', 'Best Banana exporter in United kingdom', '<p>Cultural Significance\r\nImportant in many cuisines globally, from desserts to savory dishes.\r\nSymbolizes hospitality in some cultures and plays a role in traditional ceremonies.\r\nSustainability\r\nChallenges include diseases affecting crops, such as Panama disease.</p>\r\n<p>Culinary Uses\r\nFresh Consumption: Eaten raw as a snack or added to cereals, yogurt, and salads.\r\nCooking: Used in baking (e.g., banana bread, muffins), desserts, smoothies, and savory dishes (e.g., plantains).\r\nVarieties\r\nCavendish Banana: Most common variety worldwide, typically eaten fresh.\r\nPlantains: Larger and starchier, often cooked before consumption.\r\nFun Facts\r\nBananas are technically berries botanically classified as \"false berries.\"\r\nThey are a staple food for more than 400 million people worldwide.</p>', 'A truly versatile fruit, bananas are loved by people of all ages for their taste, convenience, and health benefits.', '', 'Banana-exporter-in-United-kingdom'),
(64, 'Papaya exporter in UAE', 'Best Papaya exporter in UAE', '<p>Immune Support: High vitamin C content boosts immune function and promotes collagen synthesis for healthy skin.\n\nEye Health: Beta-carotene in papaya supports vision health and may reduce the risk of age-related macular degeneration.\n\nAnti-inflammatory Properties: Papaya\'s antioxidants, including flavonoids and vitamin C, help reduce inflammation in the body.\n\nSkin Health: Vitamin E and vitamin C in papaya contribute to skin health by promoting collagen production and protecting against oxidative damage.\n\nCulinary Uses\nFresh Consumption: Ripe papayas are typically eaten fresh, scooped out with a spoon or added to fruit salads.\nSmoothies and Juices: Papaya blends well in smoothies and juices, providing a sweet and tropical flavor.\nCooking: Green or unripe papayas are used in savory dishes, salads, and pickles.\nVarieties\nSolo Papayas: Small to medium-sized, with orange flesh and a sweet flavor.\nMaradol Papayas: Larger, oval-shaped fruits with red-orange flesh, popular in North America.</p>', ' Papaya contains the enzyme papain, which aids digestion and helps break down proteins. It may alleviate digestive issues like constipation and bloating.', '', 'Papaya-exporter-in-UAE'),
(65, 'Papaya exporter in Nepal', 'Best Papaya exporter in Nepal', '<p>Papayas are often referred to as the \"fruit of angels\" due to their sweet taste and butter-like consistency.\r\nPapaya seeds are edible and have a peppery flavor, used in some cuisines as a spice or condiment.\r\nCultural Significance\r\nPapayas are integral to Caribbean, Latin American, and Southeast Asian cuisines, used in both sweet and savory dishes.\r\nIn some cultures, papaya leaves and seeds are used for their medicinal properties.\r\nSustainability\r\nPapaya cultivation faces challenges such as diseases (e.g., papaya ringspot virus) and environmental impacts.\r\nSustainable farming practices, including integrated pest management and organic farming, are essential for papaya production.</p>', 'Whether eaten fresh, sliced into cereal or yogurt, blended into a refreshing smoothie, or baked into breads and desserts, bananas lend their deliciously sweet flavor and creamy texture to a variety of culinary creations. Beyond their culinary versatility, bananas also play a role in sustainable agriculture, providing a reliable source of income for farmers in tropical regions worldwide. ', '', 'Papaya-exporter-in-Nepal'),
(66, 'Papaya exporter in Maldives', 'Best Papaya exporter in Maldives', '<p>Digestive Health: The enzymes in papaya, particularly papain, help break down proteins and aid in digestion.\r\nRich in Antioxidants: Papayas are high in antioxidants, which help neutralize free radicals and reduce oxidative stress in the body.\r\nImmune Support: The high vitamin C content in papayas helps boost the immune system.\r\nEye Health: The beta-carotene in papayas is converted to vitamin A in the body, which is essential for eye health.\r\nCulinary Uses: Papayas can be enjoyed fresh on their own, added to fruit salads, blended into smoothies, or used in salsas and sauces. Green or unripe papaya is also used in savory dishes, such as salads (like Thai green papaya salad) or curries.</p>', 'Papaya is a tropical fruit known for its sweet flavor, vibrant color, and numerous health benefits. Here are some key points about papaya:\r\n\r\nNutritional Profile: Papayas are rich in vitamins A, C, and E, as well as folate, fiber, and potassium. They also contain enzymes like papain and chymopapain, which aid in digestion.', '', 'Papaya-exporter-in-Maldives'),
(67, 'Papaya exporter in Bhutan', 'Best Papaya exporter in Bhutan', '<p>Varieties: There are different varieties of papayas, with the two most common types being the large, oval-shaped \"Mexican\" or \"Maradol\" papaya and the smaller, round \"Hawaiian\" or \"Solo\" papaya.\r\nPapaya is a tropical fruit known for its sweet flavor, vibrant color, and numerous health benefits. Here are some key points about papaya:\r\n\r\nNutritional Profile: Papayas are rich in vitamins A, C, and E, as well as folate, fiber, and potassium. They also contain enzymes like papain and chymopapain, which aid in digestion.\r\n</p>', 'Varieties: There are different varieties of papayas, with the two most common types being the large, oval-shaped \"Mexican\" or \"Maradol\" papaya and the smaller, round \"Hawaiian\" or \"Solo\" papaya.\r\n', '', 'Papaya-exporter-in-Bhutan'),
(68, 'Papaya exporter in United Kingdom', 'Best Papaya exporter in United Kingdom', '<p>Papayas contain enzymes like papain and chymopapain, which help break down proteins and aid digestion.\r\nAntioxidant Properties: The high content of vitamins C and E, along with beta-carotene, helps protect cells from damage caused by free radicals.\r\nHeart Health: The potassium and fiber in papayas may help support heart health by lowering blood pressure and reducing cholesterol levels.\r\nCulinary Uses: Papayas can be enjoyed fresh on their own, added to fruit salads, blended into smoothies, or used in desserts like sorbets and puddings. In savory dishes, green or unripe papaya is used in salads (such as Thai green papaya salad) or cooked in curries.</p>', 'Papayas are typically large fruits with smooth, green or yellow skin that turns orange-yellow as it ripens. The flesh inside is usually orange or pinkish-orange with small, black seeds clustered in the center.\r\n', '', 'Papaya-exporter-in-United-Kingdom'),
(69, 'Papaya exporter in Singapore', 'Best Papaya exporter in Singapore', '<p>Ripening: Papayas should be allowed to ripen at room temperature until they yield to gentle pressure. Once ripe, they can be stored in the refrigerator for a few days.\r\n\r\nOverall, papayas are not only delicious but also nutritious, making them a popular choice in tropical and international cuisines.</p>', 'Ripe papayas have a sweet and musky flavor, similar to mango or cantaloupe, though less intense. The texture is soft and buttery when ripe.\r\n', '', 'Papaya-exporter-in-Singapore');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `blog`
--
ALTER TABLE `blog`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `blog`
--
ALTER TABLE `blog`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=70;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
